HTMLElement.prototype.wrap=function(_){this.parentNode.insertBefore(_,this),this.parentNode.removeChild(this),_.appendChild(this)},Fluid.events={registerNavbarEvent:function(){var _,e=jQuery("#navbar");0!==e.length&&(_=jQuery("#navbar .dropdown-menu"),0<e.offset().top&&(e.removeClass("navbar-dark"),_.removeClass("navbar-dark")),Fluid.utils.listenScroll(function(){e[50<e.offset().top?"addClass":"removeClass"]("top-nav-collapse"),_[50<e.offset().top?"addClass":"removeClass"]("dropdown-collapse"),0<e.offset().top?e.removeClass("navbar-dark"):e.addClass("navbar-dark"),_.removeClass("navbar-dark")}),jQuery("#navbar-toggler-btn").on("click",function(){jQuery(".animated-icon").toggleClass("open"),jQuery("#navbar").toggleClass("navbar-col-show")}))},registerParallaxEvent:function(){var o,r=jQuery('#banner[parallax="true"]');0!==r.length&&0!==(o=jQuery("#board")).length&&Fluid.utils.listenScroll(function(){var _=jQuery(window).scrollTop()/5,e=96+parseInt(o.css("margin-top"),10),e=(r.css({transform:"translate3d(0,"+(_=e<_?e:_)+"px,0)"}),jQuery(".side-col"));e&&e.css({"padding-top":_+"px"})})},registerScrollDownArrowEvent:function(){var _=jQuery(".scroll-down-bar");0!==_.length&&_.on("click",function(){Fluid.utils.scrollToElement("#board",-jQuery("#navbar").height())})},registerScrollTopArrowEvent:function(){var e,o,r,_,n,t=jQuery("#scroll-top-button");0!==t.length&&0!==(e=jQuery("#board")).length&&(r=o=!1,(_=function(){var _=e[0].getClientRects()[0].right,_=document.body.offsetWidth-_;o=50<=_,t.css({bottom:o&&r?"20px":"-60px",right:_-64+"px"})})(),jQuery(window).resize(_),n=e.offset().top,Fluid.utils.listenScroll(function(){var _=document.body.scrollTop+document.documentElement.scrollTop;r=n<=_,t.css({bottom:o&&r?"20px":"-60px"})}),t.on("click",function(){jQuery("body,html").animate({scrollTop:0,easing:"swing"})}))},registerImageLoadedEvent:function(){if("NProgress"in window){var _,e=document.getElementById("banner"),e=(e&&(e=e.style.backgroundImage.match(/\((.*?)\)/)[1].replace(/(['"])/g,""),(_=new Image).onload=function(){window.NProgress&&window.NProgress.inc(.2)},_.src=e,_.complete)&&_.onload(),jQuery("main img:not([lazyload])")),o=e.length;for(const _ of e){const r=_.onload;_.onload=function(){r&&r(),window.NProgress&&window.NProgress.inc(.5/o)},_.complete&&_.onload()}}},registerRefreshCallback:function(_){Array.isArray(Fluid.events._refreshCallbacks)||(Fluid.events._refreshCallbacks=[]),Fluid.events._refreshCallbacks.push(_)},refresh:function(){if(Array.isArray(Fluid.events._refreshCallbacks))for(var _ of Fluid.events._refreshCallbacks)_ instanceof Function&&_()},billboard:function(){"console"in window&&console.log(`
-------------------------------------------------------------------------------------------------------------------------------------------------------------
|                                                                                                                                                           |
|________/\\\\\\\\_____/\\\\\\\\\\_______/\\\\\\\\\\\\__/\\________/\\__/\\\\\\\\\\__/\\\\\\\\\\\\_____/\\\\\\\\\\\\\\____/\\\\\\\\_____             |
| _____/\\////////____/\\/////////\\___/\\//////////__/\\_______/\\_/////\\///__/\\////////\\__/\\///////////___/\\///////\\___            |
|  ___/\\/____________//\\______///___/\\_____________/\\_______/\\_____/\\_____/\\______//\\_/\\_____________/\\_____/\\___           |
|   __/\\_______________////\\_________/\\____/\\\\\\_/\\_______/\\_____/\\_____/\\_______/\\_/\\\\\\\\\\_____/\\\\\\\\\\/____          |
|    _/\\__________________////\\______/\\___/////\\_/\\_______/\\_____/\\_____/\\_______/\\_/\\///////______/\\//////\\____         |
|     _//\\____________________////\\___/\\_______/\\_/\\_______/\\_____/\\_____/\\_______/\\_/\\_____________/\\____//\\___        |
|      __///\\___________/\\______//\\__/\\_______/\\_//\\______/\\______/\\_____/\\_______/\\__/\\_____________/\\_____//\\__       |
|       ____////\\\\\\\\_///\\\\\\\\\\/___//\\\\\\\\\\\\/___///\\\\\\\\/____/\\\\\\\\\\_/\\\\\\\\\\\\/___/\\\\\\\\\\\\\\_/\\______//\\_      |
|        _______/////////____///////////______////////////_______/////////_____///////////__////////////_____///////////////__///________///__     |
|                                                                                                                                                           |
|                                                                    Powered by Hexo - CSGUIDER                                                             |
|                                                                 GitHub: https://github.com/wl2o2o                                                         |
|                                      maxim: 芝兰生于幽谷，不以无人而不芳，君子修道立德，不以穷困而变节!  Being different is advantage.                         |
-------------------------------------------------------------------------------------------------------------------------------------------------------------



    `)}};