name: Build and Deploy  
on: [push]  
  
jobs:  
  build-and-deploy:  
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout 🔔  
        uses: actions/checkout@v3  
          
      - name: Install Hexo CLI    
        run: npm install -g hexo-cli@4.3.0  
        env:    
          CI: false  
  
      - name: Install Dependencies # 步骤3：安装依赖  
        if: steps.cache.outputs.cache-hit != 'true'  
        run: npm run build  
        env:  
          CI: false  
            
      - name: Deploy 🚀 # 步骤4：部署  
        # uses: JamesIves/github-pages-deploy-action@releases/v3  
        uses: JamesIves/github-pages-deploy-action@v4  
        with:  
          GITHUB_TOKEN: ${{ secrets.GITEE_TOKEN }} # 使用 Gitee 令牌  
          BRANCH: master # 部署到 master 分支  
          FOLDER: public # 部署 public 文件夹