version: '1.0'
name: pipeline-20231120
displayName: hexoBlog_toMaster
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - hexoBlog
stages:
  - name: stage-1440c490
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 16.14.2
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - '# 执行编译命令'
          - npm install -g hexo-cli@4.3.0
          - ''
          - hexo cl && hexo g && hexo d
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./public
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
